# UmiJS:


image::[]


=== https://umijs.org/zh-CN/docs[UmiJS官网]
=== https://github.com/umijs/umi[UmiJS仓库]

=== UmiJS简介

> - Umi，中文可发音为乌米，是可扩展的企业级前端应用框架。
> - Umi 以路由为基础的，同时支持配置式路由和约定式路由，保证路由的功能完备，并以此进行功能扩展。
> - 然后配以生命周期完善的插件体系，覆盖从源码到构建产物的每个生命周期，支持各种功能扩展和业务需求。
> - Umi 是蚂蚁金服的底层前端框架，已直接或间接地服务了 3000+ 应用，包括 java、node、H5 无线、离线（Hybrid）应用、纯前端 assets 应用、CMS 应用等。

=== UmiJS 6大特性：

> - 🎉 可扩展，Umi 实现了完整的生命周期，并使其插件化，Umi 内部功能也全由插件完成。此外还支持插件和插件集，以满足功能和垂直域的分层需求。
> - 📦 开箱即用，Umi 内置了路由、构建、部署、测试等，仅需一个依赖即可上手开发。并且还提供针对 React 的集成插件集，内涵丰富的功能，可满足日常 80% 的开发需求。
> - 🐠 企业级，经蚂蚁内部 3000+ 项目以及阿里、优酷、网易、飞猪、口碑等公司项目的验证，值得信赖。
> - 🚀 大量自研，包含微前端、组件打包、文档工具、请求库、hooks 库、数据流等，满足日常项目的周边需求。
> - 🌴 完备路由，同时支持配置式路由和约定式路由，同时保持功能的完备性，比如动态路由、嵌套路由、权限路由等等。
> - 🚄 面向未来，在满足需求的同时，我们也不会停止对新技术的探索。比如 dll 提速、modern mode、webpack@5、自动化 external、bundler less 等等

=== 什么时候不用 Umi？

> - 需要支持 IE 8 或更低版本的浏览器
> - 需要支持 React 16.8.0 以下的 React
> - 需要跑在 Node 10 以下的环境中
> - 有很强的 webpack 自定义需求和主观意愿
> - 需要选择不同的路由方案

==== Umi 可能不适合你

=== 为什么不是？

==== create-react-app

> - create-react-app 是基于 webpack 的打包层方案，包含 build、dev、lint 等，他在打包层把体验做到了极致，但是不包含路由，不是框架，也不支持配置。
> - 所以，如果大家想基于他修改部分配置，或者希望在打包层之外也做技术收敛时，就会遇到困难。

==== next.js

> - next.js 是个很好的选择，Umi 很多功能是参考 next.js 做的。要说有哪些地方不如 Umi，我觉得可能是不够贴近业务，不够接地气。
> - 比如 antd、dva（阿里自研数据流方案）的深度整合，比如国际化、权限、数据流、配置式路由、补丁方案、自动化 external 方面等等一线开发者才会遇到的问题。


=== 约定化思想

> - 在使用umi框架的时候，很容易就发现它很多东西都是约定式的。
> - 所谓约定式就是指，按照约定好的方式开发，就能达到某种效果，中间的过程由框架帮我们完成，特别适合懒懒的开发。
> * 建一个 locales 目录，就拥有了国际化
> * 建一个 models 目录，就拥有了数据流
> * 建一个 mock 目录，就拥有了数据 mock
> * 建一个 access.ts 文件，就拥有了权限策略 
> - 这种方式对于团队代码风格的统一是非常有好处的，直接在框架层面就约束了大家的目录组织模式，便于团队维护

=== UmiJS 背后的思考和概念

=== 技术收敛

image::[]

> - 这张图是给内部框架 Bigfish 画的，套到 Umi 上同样合适。他把大家常用的技术栈进行整理，收敛到一起，让大家只用 Umi 就可以完成 80% 的日常工作。

=== 插件体系

image::[]

可以说插件体系是 Umi 最重要的基建，因为包括 Umi内部实现也是全部由插件构成


=== 3.x版本的变化

> - 彻底重写的代码和文档，80%+ 的覆盖率，~100M 的尺寸
> - 官方插件、插件集和最佳实践
> - 更智能（CSS Modules 的自动识别、约定式路由的改进等）
> - Import “所有” from Umi。通过插件扩展 import from umi 的能力
> - node_modules 走 babel 编译 ...

---


=== 快速上手

> - (1)安装脚手架

```jsx
  mkdir react-umi && cd react-umi //空目录 
  npx @umijs/create-umi-app
```

> - (2)安装依赖

```jsx
  npm i
```


> - (3)运行


```jsx
  npm start
```

image::[]

---


=== 项目目录

> - 项目初始化后，默认的目录结构如下：

----
  .
  ├── package.json
  ├── .umirc.ts 配置文件，包含 umi 内置功能和插件的配置。
  ├── .env 环境变量
  ├── dist 执行 umi build 后，产物默认会存放在这里
  ├── mock 存储 mock 文件，此目录下所有 js 和 ts 文件会被解析为 mock 文件
  ├── public 此目录下所有文件会被 copy 到输出路径
  └── src
      ├── .umi 临时文件目录，比如入口文件、路由等，都会被临时生成到这里
      ├── layouts/index.tsx 约定式路由时的全局布局文件
      ├── pages 所有路由组件存放在这里
          ├── index.less
          └── index.tsx
      └── app.ts 运行时配置文件，可以在这里扩展运行时的能力，比如修改路由、修改 render 方法等
----

最重要的文件是.umirc.ts配置文件，在里面可以配置各种功能和插件，umi支持不同环境读取不同的配置文件


---

---

=== 案例(卖座)

image::[]


=== 约定式路由

约定式路由也叫文件路由，就是不需要手写配置，文件系统即路由，通过src/pages目录和文件及其命名分析出路由配置, 也就是让umi根据约定好的目录结构帮我们生成路由配置文件。


比如以下文件结构：


----

├── pages
  ├── 404.tsx
  ├── center.tsx
  ├── cinema.tsx
  ├── city.tsx
  ├── detail
  │   └── [id].tsx
  ├── film
  │   ├── _layout.tsx
  │   ├── comingsoon.tsx
  │   └── nowplaying.tsx
  ├── index.tsx
  └── login.tsx

----

会得到以下路由配置

----
[
  { exact: true, path: '/', component: '@/pages/index' },
  { exact: true, path: '/login', component: '@/pages/login' },
  { exact: true, path: '/city', component: '@/pages/city' }
  ...
]
----

> - 需要注意的是，满足以下任意规则的文件不会被注册为路由
> * 以.或_开头的文件或目录
> * 以d.ts结尾的类型定义文件
> * 以test.ts、spec.ts、e2e.ts结尾的测试文件（适用于.js、.jsx和.tsx文件）
> * components和component目录
> * utils和util目录
> * 不是.js、.jsx、.ts或.tsx文件
> * 文件内容不包含 JSX 元素

> - (1) 基础路由

image::[]

> - (2) 重定向

image::[]

```tsx
```

> - (3) 嵌套路由

image::[]

```tsx
```

> - (4) 动态路由

image::[]

> - (5) 路由拦截

```tsx
```

> - (6) hash模式

```tsx
// 在.umirc.js

```

> - (7) 声明式导航

image::[]

```tsx
```

> - (8) 编程式导航

```tsx
```

---



